Algoritmo "Operadores aritméticos"
// Descrição   : Operações aritméticas
// Autor(a)    : Lucas
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 
   resultado, valor01, valor02, valor03:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         valor01 := 10
         valor02 := 10
         valor03 := 10
         resultado := ((valor01 + valor02 + valor02) / valor03) % 2
          escreval ("esse foi o resultado: ", resultado)

Fimalgoritmo