Algoritmo "Operadores de Concatenação"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 
    nome: caractere
    numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("digite seu nome")
   leia(nome)
   escreval("digite seu número")
   leia(numero)

   escreval(nome, " : ", numero)
Fimalgoritmo