Algoritmo "Operadores relacionais"

// Descrição   : Operações relacionadas
// Autor(a)    : Lucas
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 
     nota01, nota02:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         nota01 := 10
         nota02 := 15
se (nota01 <> nota02)entao
   escreval("nota01 é diferente")
senao
     escreval("nota01 é igual")
fimse

Fimalgoritmo